name: Currency Converter
version: 1.0.1
description: Converter as many currencies as you wish
addon_url: https://statamic.com/addons/currencyconverter
developer: Andreas Schantl
developer_url: https://schantl.io